from youtube_transcript_api import YouTubeTranscriptApi

video_id = "htiNBPxcXgo"

ytt_api = YouTubeTranscriptApi()

# retrieve the available transcripts
transcript_list = ytt_api.list(video_id)

transcript = transcript_list.find_transcript(['en'])
# # iterate over all available transcripts
# for transcript in transcript_list:

#     # the Transcript object provides metadata properties
#     print(
#         transcript.video_id,
#         transcript.language,
#         transcript.language_code,
#         # whether it has been manually created or generated by YouTube
#         transcript.is_generated,
#         # whether this transcript can be translated or not
#         transcript.is_translatable,
#         # a list of languages the transcript can be translated to
#         transcript.translation_languages,
#     )
lines= transcript.fetch()

with open("./data/transcripts/transcript_lec_8.txt", "w" , encoding="utf-8") as f:
    for line in lines:
        f.write(line.text + '\n')

print("Transcript saved")